language: python
python:
  - "2.7"
  # PyPy versions
  - "pypy"   # PyPy2 5.8.0
# command to install dependencies
install:
  - pip install .
  - pip install -r requirements.txt
  - pip install nose
# command to run tests
script: python setup.py test 
